name: Manual Run D1_LSTM.py

on:
  workflow_dispatch:  # Pozwala na ręczne uruchamianie workflow

jobs:
  run-lstm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Wybierz odpowiednią wersję Pythona

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Zakładając, że masz plik requirements.txt
        pip install git+https://github.com/statsmodels/statsmodels.git

    - name: Run D1_LSTM.py
      run: python D1_LSTM.py

    - name: Save results
      run: |
        mkdir -p artifacts
        cp D1_EUR_a.pkl artifacts/
        cp D1_USD_a.pkl artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: artifacts/

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add artifacts/D1_EUR_a.pkl artifacts/D1_USD_a.pkl
        git commit -m 'Add results from D1_LSTM.py'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
