name: Run D5_LSTM.py

on:
  schedule:
    - cron: '30 7 * * 4'  # W czwartki o 7:30 UTC (9:30 czasu warszawskiego)

jobs:
  run-lstm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Wybierz odpowiednią wersję Pythona

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Zakładając, że masz plik requirements.txt
        pip install git+https://github.com/statsmodels/statsmodels.git

    - name: Run D5_LSTM.py
      run: python D5_LSTM.py

    - name: Save results
      run: |
        mkdir -p artifacts
        cp _fore_D5.pkl artifacts/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: artifacts/

    - name: Pull latest changes
      run: git pull origin master
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add artifacts/_fore_D5.pkl 
        git commit -m 'Add results from D5_LSTM.py'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}

    - name: Move files
      run: |
        mv artifacts/D1_EUR_a.pkl .
        mv artifacts/D1_USD_a.pkl .
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add _fore_D5.pkl 
        git commit -m 'Move _fore_D5.pkl from artifacts to root directory'
        git push origin master  
    env:
        GITHUB_TOKEN: ${{ secrets.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 }}   
